//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tei_tax_update_logs
    {
        public int ID { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public string Descr { get; set; }
        public string ErrorLevel { get; set; }
        public string StackTrace { get; set; }
    }
}
