//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcumaticaTaxUpdate
{
    using System;
    using System.Collections.Generic;
    
    public partial class tei_tax_rates
    {
        public int Id { get; set; }
        public string z2t_ID { get; set; }
        public string ZipCode { get; set; }
        public string TaxRate { get; set; }
        public string TaxType { get; set; }
        public string RateState { get; set; }
        public string ReportingCodeState { get; set; }
        public string RateCounty { get; set; }
        public string ReportingCodeCounty { get; set; }
        public string RateCity { get; set; }
        public string ReportingCodeCity { get; set; }
        public string RateSpecialDistrict { get; set; }
        public string ReportingCodeSpecialDistrict { get; set; }
        public string City { get; set; }
        public string PostOffice { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string ShippingTaxable { get; set; }
        public string PrimaryRecord { get; set; }
        public Nullable<System.DateTime> StateUpdated { get; set; }
        public Nullable<System.DateTime> CountyUpdated { get; set; }
        public Nullable<System.DateTime> SDUpdated { get; set; }
        public Nullable<System.DateTime> CityUpdated { get; set; }
    }
}
