//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcumaticaTaxUpdate
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Taxes_To_Update
    {
        public string TaxID { get; set; }
        public string Description { get; set; }
        public string Tax_Type { get; set; }
        public string TaxRate { get; set; }
        public string Reporting_Group { get; set; }
        public string z2t_ID { get; set; }
    }
}
